# Polarsの基礎
下記を参考に色々動かしてみる。  
適宜pandasとの違いも見る。  
https://qiita.com/_jinta/items/28442d25bba067c13bb7

In [1]:
!pip install polars

Collecting polars
  Downloading polars-0.16.6-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 3.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: typing_extensions>=4.0.1 in /opt/anaconda3/lib/python3.9/site-packages (from polars) (4.1.1)
Installing collected packages: polars
Successfully installed polars-0.16.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.2 -> 23.0
[notice] To update, run: pip install --upgrade pip

In [18]:
import polars as pl
import pandas as pd
import os
from pathlib import Path
from glob import glob

##  データサイエンス100本ノック（構造化データ加工編）でお試し

In [96]:
# データがあるディレクトリへのパス指定
paths = Path('../../../100knocks-preprocess/docker/work/data/').glob('*.csv')
csv_list = [os.path.split(file) for file in paths]

In [90]:
csv_list

[('../../../100knocks-preprocess/docker/work/data', 'store.csv'),
 ('../../../100knocks-preprocess/docker/work/data', 'receipt.csv'),
 ('../../../100knocks-preprocess/docker/work/data', 'category.csv'),
 ('../../../100knocks-preprocess/docker/work/data', 'product.csv'),
 ('../../../100knocks-preprocess/docker/work/data', 'customer.csv'),
 ('../../../100knocks-preprocess/docker/work/data', 'geocode.csv')]

In [107]:
dtypes = {
    'customer_id': str,
    'gender_cd': str,
    'postal_cd': str,
    'application_store_cd': str,
    'status_cd': str,
    'category_major_cd': str,
    'category_medium_cd': str,
    'category_small_cd': str,
    'product_cd': str,
    'store_cd': str,
    'prefecture_cd': str,
    'tel_no': str,
    'postal_cd': str,
    'street': str,
    'application_date': str,
    'birth_day': pl.Date
}

# 複数のdfを辞書型に格納。理由は変数名ごとにread_csvするのが嫌だから。
df_dict = {}
for path, file in csv_list:
    file_name = file[:-4]
    df_dict[file_name] = pl.read_csv(os.path.join(path, file), dtypes=dtypes)

In [109]:
# レシートデータの先頭10件を確認
df_dict['receipt'].head(10)

shape: (10, 9)
┌───────────┬───────────┬──────────┬──────────┬─────┬───────────┬──────────────┬──────────┬────────┐
│ sales_ymd ┆ sales_epo ┆ store_cd ┆ receipt_ ┆ ... ┆ customer_ ┆ product_cd   ┆ quantity ┆ amount │
│ ---       ┆ ch        ┆ ---      ┆ no       ┆     ┆ id        ┆ ---          ┆ ---      ┆ ---    │
│ i64       ┆ ---       ┆ str      ┆ ---      ┆     ┆ ---       ┆ str          ┆ i64      ┆ i64    │
│           ┆ i64       ┆          ┆ i64      ┆     ┆ str       ┆              ┆          ┆        │
╞═══════════╪═══════════╪══════════╪══════════╪═════╪═══════════╪══════════════╪══════════╪════════╡
│ 20181103  ┆ 154120320 ┆ S14006   ┆ 112      ┆ ... ┆ CS0062140 ┆ P070305012   ┆ 1        ┆ 158    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00001     ┆              ┆          ┆        │
│ 20181118  ┆ 154249920 ┆ S13008   ┆ 1132     ┆ ... ┆ CS0084150 ┆ P070701017   ┆ 1        ┆ 81     │
│           ┆ 0         ┆          ┆          ┆     ┆ 00097     ┆              ┆          ┆        │
│ 20170712  ┆ 149981760 ┆ S14028   ┆ 1102     ┆ ... ┆ CS0284140 ┆ P060101005   ┆ 1        ┆ 170    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00014     ┆              ┆          ┆        │
│ 20190205  ┆ 154932480 ┆ S14042   ┆ 1132     ┆ ... ┆ ZZ0000000 ┆ P050301001   ┆ 1        ┆ 25     │
│           ┆ 0         ┆          ┆          ┆     ┆ 00000     ┆              ┆          ┆        │
│ ...       ┆ ...       ┆ ...      ┆ ...      ┆ ... ┆ ...       ┆ ...          ┆ ...      ┆ ...    │
│ 20181205  ┆ 154396800 ┆ S14024   ┆ 1102     ┆ ... ┆ CS0245140 ┆ P080101005   ┆ 1        ┆ 30     │
│           ┆ 0         ┆          ┆          ┆     ┆ 00042     ┆              ┆          ┆        │
│ 20190922  ┆ 156911040 ┆ S14040   ┆ 1102     ┆ ... ┆ CS0404150 ┆ P070501004   ┆ 1        ┆ 128    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00178     ┆              ┆          ┆        │
│ 20170504  ┆ 149385600 ┆ S13020   ┆ 1112     ┆ ... ┆ ZZ0000000 ┆ P071302010   ┆ 1        ┆ 770    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00000     ┆              ┆          ┆        │
│ 20191010  ┆ 157066560 ┆ S14027   ┆ 1102     ┆ ... ┆ CS0275140 ┆ P071101003   ┆ 1        ┆ 680    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00015     ┆              ┆          ┆        │
└───────────┴───────────┴──────────┴──────────┴─────┴───────────┴──────────────┴──────────┴────────┘

In [122]:
# indexはないが、pandasのように書くことも可能。iloc,locは存在しない。
df_dict['receipt'][0:5]

shape: (5, 9)
┌───────────┬───────────┬──────────┬──────────┬─────┬───────────┬──────────────┬──────────┬────────┐
│ sales_ymd ┆ sales_epo ┆ store_cd ┆ receipt_ ┆ ... ┆ customer_ ┆ product_cd   ┆ quantity ┆ amount │
│ ---       ┆ ch        ┆ ---      ┆ no       ┆     ┆ id        ┆ ---          ┆ ---      ┆ ---    │
│ i64       ┆ ---       ┆ str      ┆ ---      ┆     ┆ ---       ┆ str          ┆ i64      ┆ i64    │
│           ┆ i64       ┆          ┆ i64      ┆     ┆ str       ┆              ┆          ┆        │
╞═══════════╪═══════════╪══════════╪══════════╪═════╪═══════════╪══════════════╪══════════╪════════╡
│ 20181103  ┆ 154120320 ┆ S14006   ┆ 112      ┆ ... ┆ CS0062140 ┆ P070305012   ┆ 1        ┆ 158    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00001     ┆              ┆          ┆        │
│ 20181118  ┆ 154249920 ┆ S13008   ┆ 1132     ┆ ... ┆ CS0084150 ┆ P070701017   ┆ 1        ┆ 81     │
│           ┆ 0         ┆          ┆          ┆     ┆ 00097     ┆              ┆          ┆        │
│ 20170712  ┆ 149981760 ┆ S14028   ┆ 1102     ┆ ... ┆ CS0284140 ┆ P060101005   ┆ 1        ┆ 170    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00014     ┆              ┆          ┆        │
│ 20190205  ┆ 154932480 ┆ S14042   ┆ 1132     ┆ ... ┆ ZZ0000000 ┆ P050301001   ┆ 1        ┆ 25     │
│           ┆ 0         ┆          ┆          ┆     ┆ 00000     ┆              ┆          ┆        │
│ 20180821  ┆ 153480960 ┆ S14025   ┆ 1102     ┆ ... ┆ CS0254150 ┆ P060102007   ┆ 1        ┆ 90     │
│           ┆ 0         ┆          ┆          ┆     ┆ 00050     ┆              ┆          ┆        │
└───────────┴───────────┴──────────┴──────────┴─────┴───────────┴──────────────┴──────────┴────────┘

In [123]:
df_dict['receipt'].columns

['sales_ymd',
 'sales_epoch',
 'store_cd',
 'receipt_no',
 'receipt_sub_no',
 'customer_id',
 'product_cd',
 'quantity',
 'amount']

In [117]:
# 任意の列を選択して表示。.selectを使うのが推奨。
cols = ['sales_ymd','customer_id', 'product_cd', 'amount']
df_dict['receipt'].select(cols).head(10)

shape: (10, 4)
┌───────────┬────────────────┬────────────┬────────┐
│ sales_ymd ┆ customer_id    ┆ product_cd ┆ amount │
│ ---       ┆ ---            ┆ ---        ┆ ---    │
│ i64       ┆ str            ┆ str        ┆ i64    │
╞═══════════╪════════════════╪════════════╪════════╡
│ 20181103  ┆ CS006214000001 ┆ P070305012 ┆ 158    │
│ 20181118  ┆ CS008415000097 ┆ P070701017 ┆ 81     │
│ 20170712  ┆ CS028414000014 ┆ P060101005 ┆ 170    │
│ 20190205  ┆ ZZ000000000000 ┆ P050301001 ┆ 25     │
│ ...       ┆ ...            ┆ ...        ┆ ...    │
│ 20181205  ┆ CS024514000042 ┆ P080101005 ┆ 30     │
│ 20190922  ┆ CS040415000178 ┆ P070501004 ┆ 128    │
│ 20170504  ┆ ZZ000000000000 ┆ P071302010 ┆ 770    │
│ 20191010  ┆ CS027514000015 ┆ P071101003 ┆ 680    │
└───────────┴────────────────┴────────────┴────────┘

In [127]:
# .filterはpandasの.queryみたいな感じ。pl.col(列名)で列を選択する。locの列指定みたいな感じ。
df_dict['receipt'].filter(pl.col('amount') > 200).head()

shape: (5, 9)
┌───────────┬───────────┬──────────┬──────────┬─────┬───────────┬──────────────┬──────────┬────────┐
│ sales_ymd ┆ sales_epo ┆ store_cd ┆ receipt_ ┆ ... ┆ customer_ ┆ product_cd   ┆ quantity ┆ amount │
│ ---       ┆ ch        ┆ ---      ┆ no       ┆     ┆ id        ┆ ---          ┆ ---      ┆ ---    │
│ i64       ┆ ---       ┆ str      ┆ ---      ┆     ┆ ---       ┆ str          ┆ i64      ┆ i64    │
│           ┆ i64       ┆          ┆ i64      ┆     ┆ str       ┆              ┆          ┆        │
╞═══════════╪═══════════╪══════════╪══════════╪═════╪═══════════╪══════════════╪══════════╪════════╡
│ 20170504  ┆ 149385600 ┆ S13020   ┆ 1112     ┆ ... ┆ ZZ0000000 ┆ P071302010   ┆ 1        ┆ 770    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00000     ┆              ┆          ┆        │
│ 20191010  ┆ 157066560 ┆ S14027   ┆ 1102     ┆ ... ┆ CS0275140 ┆ P071101003   ┆ 1        ┆ 680    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00015     ┆              ┆          ┆        │
│ 20171010  ┆ 150759360 ┆ S14021   ┆ 1162     ┆ ... ┆ CS0215150 ┆ P040402001   ┆ 1        ┆ 228    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00126     ┆              ┆          ┆        │
│ 20180506  ┆ 152556480 ┆ S13039   ┆ 1112     ┆ ... ┆ CS0394140 ┆ P059001019   ┆ 1        ┆ 428    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00052     ┆              ┆          ┆        │
│ 20190326  ┆ 155355840 ┆ S13016   ┆ 112      ┆ ... ┆ CS0162150 ┆ P091401190   ┆ 1        ┆ 780    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00032     ┆              ┆          ┆        │
└───────────┴───────────┴──────────┴──────────┴─────┴───────────┴──────────────┴──────────┴────────┘

In [130]:
# 複数条件
df_dict['receipt'].filter( (pl.col('amount') > 200) & (pl.col('quantity') > 1) ).head()

shape: (5, 9)
┌───────────┬───────────┬──────────┬──────────┬─────┬───────────┬──────────────┬──────────┬────────┐
│ sales_ymd ┆ sales_epo ┆ store_cd ┆ receipt_ ┆ ... ┆ customer_ ┆ product_cd   ┆ quantity ┆ amount │
│ ---       ┆ ch        ┆ ---      ┆ no       ┆     ┆ id        ┆ ---          ┆ ---      ┆ ---    │
│ i64       ┆ ---       ┆ str      ┆ ---      ┆     ┆ ---       ┆ str          ┆ i64      ┆ i64    │
│           ┆ i64       ┆          ┆ i64      ┆     ┆ str       ┆              ┆          ┆        │
╞═══════════╪═══════════╪══════════╪══════════╪═════╪═══════════╪══════════════╪══════════╪════════╡
│ 20170616  ┆ 149757120 ┆ S12030   ┆ 1182     ┆ ... ┆ CS0305150 ┆ P040503001   ┆ 2        ┆ 596    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00078     ┆              ┆          ┆        │
│ 20191017  ┆ 157127040 ┆ S13004   ┆ 1182     ┆ ... ┆ CS0044130 ┆ P071401002   ┆ 2        ┆ 2200   │
│           ┆ 0         ┆          ┆          ┆     ┆ 00039     ┆              ┆          ┆        │
│ 20180607  ┆ 152832960 ┆ S14022   ┆ 1112     ┆ ... ┆ CS0225120 ┆ P050603001   ┆ 2        ┆ 336    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00070     ┆              ┆          ┆        │
│ 20180607  ┆ 152832960 ┆ S14045   ┆ 1142     ┆ ... ┆ ZZ0000000 ┆ P060303001   ┆ 2        ┆ 296    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00000     ┆              ┆          ┆        │
│ 20180508  ┆ 152573760 ┆ S13004   ┆ 112      ┆ ... ┆ CS0042150 ┆ P060303001   ┆ 2        ┆ 296    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00154     ┆              ┆          ┆        │
└───────────┴───────────┴──────────┴──────────┴─────┴───────────┴──────────────┴──────────┴────────┘

In [134]:
# 条件を変数に格納してフィルタリングも可能。
condition = (pl.col('amount') > 200) & (pl.col('quantity') > 1)
df_dict['receipt'].filter(condition).head()

shape: (5, 9)
┌───────────┬───────────┬──────────┬──────────┬─────┬───────────┬──────────────┬──────────┬────────┐
│ sales_ymd ┆ sales_epo ┆ store_cd ┆ receipt_ ┆ ... ┆ customer_ ┆ product_cd   ┆ quantity ┆ amount │
│ ---       ┆ ch        ┆ ---      ┆ no       ┆     ┆ id        ┆ ---          ┆ ---      ┆ ---    │
│ i64       ┆ ---       ┆ str      ┆ ---      ┆     ┆ ---       ┆ str          ┆ i64      ┆ i64    │
│           ┆ i64       ┆          ┆ i64      ┆     ┆ str       ┆              ┆          ┆        │
╞═══════════╪═══════════╪══════════╪══════════╪═════╪═══════════╪══════════════╪══════════╪════════╡
│ 20170616  ┆ 149757120 ┆ S12030   ┆ 1182     ┆ ... ┆ CS0305150 ┆ P040503001   ┆ 2        ┆ 596    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00078     ┆              ┆          ┆        │
│ 20191017  ┆ 157127040 ┆ S13004   ┆ 1182     ┆ ... ┆ CS0044130 ┆ P071401002   ┆ 2        ┆ 2200   │
│           ┆ 0         ┆          ┆          ┆     ┆ 00039     ┆              ┆          ┆        │
│ 20180607  ┆ 152832960 ┆ S14022   ┆ 1112     ┆ ... ┆ CS0225120 ┆ P050603001   ┆ 2        ┆ 336    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00070     ┆              ┆          ┆        │
│ 20180607  ┆ 152832960 ┆ S14045   ┆ 1142     ┆ ... ┆ ZZ0000000 ┆ P060303001   ┆ 2        ┆ 296    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00000     ┆              ┆          ┆        │
│ 20180508  ┆ 152573760 ┆ S13004   ┆ 112      ┆ ... ┆ CS0042150 ┆ P060303001   ┆ 2        ┆ 296    │
│           ┆ 0         ┆          ┆          ┆     ┆ 00154     ┆              ┆          ┆        │
└───────────┴───────────┴──────────┴──────────┴─────┴───────────┴──────────────┴──────────┴────────┘

In [136]:
# 一部の列名を変更したうえで、複数列を選択
df_dict['receipt'].select([
    pl.col('sales_ymd').alias('sales_date'), 'customer_id', 'product_cd', 'amount'
]).head(10)

shape: (10, 4)
┌────────────┬────────────────┬────────────┬────────┐
│ sales_date ┆ customer_id    ┆ product_cd ┆ amount │
│ ---        ┆ ---            ┆ ---        ┆ ---    │
│ i64        ┆ str            ┆ str        ┆ i64    │
╞════════════╪════════════════╪════════════╪════════╡
│ 20181103   ┆ CS006214000001 ┆ P070305012 ┆ 158    │
│ 20181118   ┆ CS008415000097 ┆ P070701017 ┆ 81     │
│ 20170712   ┆ CS028414000014 ┆ P060101005 ┆ 170    │
│ 20190205   ┆ ZZ000000000000 ┆ P050301001 ┆ 25     │
│ ...        ┆ ...            ┆ ...        ┆ ...    │
│ 20181205   ┆ CS024514000042 ┆ P080101005 ┆ 30     │
│ 20190922   ┆ CS040415000178 ┆ P070501004 ┆ 128    │
│ 20170504   ┆ ZZ000000000000 ┆ P071302010 ┆ 770    │
│ 20191010   ┆ CS027514000015 ┆ P071101003 ┆ 680    │
└────────────┴────────────────┴────────────┴────────┘

In [140]:
#pandasのqueryに相当する捜査はselect,filterの組み合わせで行う。
df_dict['receipt'].select(cols).filter(pl.col('customer_id') == 'CS018205000001')

shape: (12, 4)
┌───────────┬────────────────┬────────────┬────────┐
│ sales_ymd ┆ customer_id    ┆ product_cd ┆ amount │
│ ---       ┆ ---            ┆ ---        ┆ ---    │
│ i64       ┆ str            ┆ str        ┆ i64    │
╞═══════════╪════════════════╪════════════╪════════╡
│ 20180911  ┆ CS018205000001 ┆ P071401012 ┆ 2200   │
│ 20180414  ┆ CS018205000001 ┆ P060104007 ┆ 600    │
│ 20170614  ┆ CS018205000001 ┆ P050206001 ┆ 990    │
│ 20170614  ┆ CS018205000001 ┆ P060702015 ┆ 108    │
│ ...       ┆ ...            ┆ ...        ┆ ...    │
│ 20190226  ┆ CS018205000001 ┆ P071401020 ┆ 2200   │
│ 20180911  ┆ CS018205000001 ┆ P071401005 ┆ 1100   │
│ 20190216  ┆ CS018205000001 ┆ P040101002 ┆ 218    │
│ 20190924  ┆ CS018205000001 ┆ P091503001 ┆ 280    │
└───────────┴────────────────┴────────────┴────────┘

In [148]:
# 顧客IDと売上金額でフィルタリング。複数条件のフィルタリングは下記のように書く。
df_dict['receipt'].select(cols).filter(
    (pl.col('customer_id') == 'CS018205000001') &
    (pl.col('amount') > 1000)
)

shape: (3, 4)
┌───────────┬────────────────┬────────────┬────────┐
│ sales_ymd ┆ customer_id    ┆ product_cd ┆ amount │
│ ---       ┆ ---            ┆ ---        ┆ ---    │
│ i64       ┆ str            ┆ str        ┆ i64    │
╞═══════════╪════════════════╪════════════╪════════╡
│ 20180911  ┆ CS018205000001 ┆ P071401012 ┆ 2200   │
│ 20190226  ┆ CS018205000001 ┆ P071401020 ┆ 2200   │
│ 20180911  ┆ CS018205000001 ┆ P071401005 ┆ 1100   │
└───────────┴────────────────┴────────────┴────────┘

In [149]:
# もう少し複雑な場合のフィルタリング
cols = ['sales_ymd','customer_id', 'product_cd', 'quantity','amount']

df_dict['receipt'].select(cols).filter(
    (pl.col('customer_id') == 'CS018205000001') &
    ((pl.col('amount') >= 1000) | (pl.col('quantity') >= 5))
)

shape: (5, 5)
┌───────────┬────────────────┬────────────┬──────────┬────────┐
│ sales_ymd ┆ customer_id    ┆ product_cd ┆ quantity ┆ amount │
│ ---       ┆ ---            ┆ ---        ┆ ---      ┆ ---    │
│ i64       ┆ str            ┆ str        ┆ i64      ┆ i64    │
╞═══════════╪════════════════╪════════════╪══════════╪════════╡
│ 20180911  ┆ CS018205000001 ┆ P071401012 ┆ 1        ┆ 2200   │
│ 20180414  ┆ CS018205000001 ┆ P060104007 ┆ 6        ┆ 600    │
│ 20170614  ┆ CS018205000001 ┆ P050206001 ┆ 5        ┆ 990    │
│ 20190226  ┆ CS018205000001 ┆ P071401020 ┆ 1        ┆ 2200   │
│ 20180911  ┆ CS018205000001 ┆ P071401005 ┆ 1        ┆ 1100   │
└───────────┴────────────────┴────────────┴──────────┴────────┘

In [156]:
# amountが1000以上2000以下の場合。
# .is_betweenで範囲指定する
df_dict['receipt'].select(cols).filter(
    (pl.col('customer_id') == 'CS018205000001') &
    ((pl.col('amount').is_between(1000, 2000)) | (pl.col('quantity') >= 5))
)

shape: (3, 5)
┌───────────┬────────────────┬────────────┬──────────┬────────┐
│ sales_ymd ┆ customer_id    ┆ product_cd ┆ quantity ┆ amount │
│ ---       ┆ ---            ┆ ---        ┆ ---      ┆ ---    │
│ i64       ┆ str            ┆ str        ┆ i64      ┆ i64    │
╞═══════════╪════════════════╪════════════╪══════════╪════════╡
│ 20180414  ┆ CS018205000001 ┆ P060104007 ┆ 6        ┆ 600    │
│ 20170614  ┆ CS018205000001 ┆ P050206001 ┆ 5        ┆ 990    │
│ 20180911  ┆ CS018205000001 ┆ P071401005 ┆ 1        ┆ 1100   │
└───────────┴────────────────┴────────────┴──────────┴────────┘

下記のようなpandasのqueryのような書き方はできず、エラーになる。  
.is_betweenはあまり直感的ではないけど、慣れの問題かも。

In [150]:
# df_dict['receipt'].select(cols).filter(
#     (pl.col('customer_id') == 'CS018205000001') &
#     (1000 <= pl.col('amount') <= 2000)
# )

ValueError: Since Expr are lazy, the truthiness of an Expr is ambiguous. Hint: use '&' or '|' to logically combine Expr, not 'and'/'or', and use 'x.is_in([y,z])' instead of 'x in [y,z]' to check membership.

In [159]:
#店舗データ（df_store）から、店舗コード（store_cd）が"S14"で始まるものだけ全項目抽出し、5件表示
df_dict['store'].filter(pl.col('store_cd').str.starts_with('S14')).head(5)

shape: (5, 10)
┌──────────┬──────────┬────────────┬──────────┬─────┬────────────┬───────────┬──────────┬──────────┐
│ store_cd ┆ store_na ┆ prefecture ┆ prefectu ┆ ... ┆ tel_no     ┆ longitude ┆ latitude ┆ floor_ar │
│ ---      ┆ me       ┆ _cd        ┆ re       ┆     ┆ ---        ┆ ---       ┆ ---      ┆ ea       │
│ str      ┆ ---      ┆ ---        ┆ ---      ┆     ┆ str        ┆ f64       ┆ f64      ┆ ---      │
│          ┆ str      ┆ str        ┆ str      ┆     ┆            ┆           ┆          ┆ f64      │
╞══════════╪══════════╪════════════╪══════════╪═════╪════════════╪═══════════╪══════════╪══════════╡
│ S14010   ┆ 菊名店   ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.6326  ┆ 35.50049 ┆ 1732.0   │
│          ┆          ┆            ┆          ┆     ┆ 32         ┆           ┆          ┆          │
│ S14033   ┆ 阿久和店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4961  ┆ 35.45918 ┆ 1495.0   │
│          ┆          ┆            ┆          ┆     ┆ 43         ┆           ┆          ┆          │
│ S14036   ┆ 相模原中 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 042-123-40 ┆ 139.3716  ┆ 35.57327 ┆ 1679.0   │
│          ┆ 央店     ┆            ┆          ┆     ┆ 45         ┆           ┆          ┆          │
│ S14040   ┆ 長津田店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4994  ┆ 35.52398 ┆ 1548.0   │
│          ┆          ┆            ┆          ┆     ┆ 46         ┆           ┆          ┆          │
│ S14050   ┆ 阿久和西 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4961  ┆ 35.45918 ┆ 1830.0   │
│          ┆ 店       ┆            ┆          ┆     ┆ 53         ┆           ┆          ┆          │
└──────────┴──────────┴────────────┴──────────┴─────┴────────────┴───────────┴──────────┴──────────┘

In [160]:
#顧客データ（df_customer）から顧客ID（customer_id）の末尾が1のものだけ全項目抽出し、5件表示
df_dict['customer'].filter(pl.col('customer_id').str.ends_with('1')).head(5)

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────┬─────┬──────────┬────────────┬────────────┬─────────┐
│ customer_ ┆ customer_n ┆ gender_cd ┆ gender ┆ ... ┆ address  ┆ applicatio ┆ applicatio ┆ status_ │
│ id        ┆ ame        ┆ ---       ┆ ---    ┆     ┆ ---      ┆ n_store_cd ┆ n_date     ┆ cd      │
│ ---       ┆ ---        ┆ str       ┆ str    ┆     ┆ str      ┆ ---        ┆ ---        ┆ ---     │
│ str       ┆ str        ┆           ┆        ┆     ┆          ┆ str        ┆ str        ┆ str     │
╞═══════════╪════════════╪═══════════╪════════╪═════╪══════════╪════════════╪════════════╪═════════╡
│ CS0376130 ┆ 六角 雅彦  ┆ 9         ┆ 不明   ┆ ... ┆ 東京都江 ┆ S13037     ┆ 20150414   ┆ 0-00000 │
│ 00071     ┆            ┆           ┆        ┆     ┆ 東区南砂 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0288110 ┆ 堀井       ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14028     ┆ 20160115   ┆ 0-00000 │
│ 00001     ┆ かおり     ┆           ┆        ┆     ┆ 横浜市泉 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 区和泉町 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0404120 ┆ 川井 郁恵  ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14040     ┆ 20151101   ┆ 1-20091 │
│ 00191     ┆            ┆           ┆        ┆     ┆ 横浜市緑 ┆            ┆            ┆ 025-4   │
│           ┆            ┆           ┆        ┆     ┆ 区北八朔 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ 町****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0283140 ┆ 小菅       ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14028     ┆ 20151123   ┆ 1-20080 │
│ 00011     ┆ あおい     ┆           ┆        ┆     ┆ 横浜市瀬 ┆            ┆            ┆ 426-5   │
│           ┆            ┆           ┆        ┆     ┆ 谷区宮沢 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0392120 ┆ 藤島       ┆ 1         ┆ 女性   ┆ ... ┆ 東京都杉 ┆ S13039     ┆ 20171121   ┆ 1-20100 │
│ 00051     ┆ 恵梨香     ┆           ┆        ┆     ┆ 並区阿佐 ┆            ┆            ┆ 215-4   │
│           ┆            ┆           ┆        ┆     ┆ 谷北**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
└───────────┴────────────┴───────────┴────────┴─────┴──────────┴────────────┴────────────┴─────────┘

In [162]:
#店舗データ（df_store）から、住所 (address) に"横浜市"が含まれるものだけ全項目表示
df_dict['store'].filter(pl.col('address').str.contains('横浜市'))

shape: (11, 10)
┌──────────┬──────────┬────────────┬──────────┬─────┬────────────┬───────────┬──────────┬──────────┐
│ store_cd ┆ store_na ┆ prefecture ┆ prefectu ┆ ... ┆ tel_no     ┆ longitude ┆ latitude ┆ floor_ar │
│ ---      ┆ me       ┆ _cd        ┆ re       ┆     ┆ ---        ┆ ---       ┆ ---      ┆ ea       │
│ str      ┆ ---      ┆ ---        ┆ ---      ┆     ┆ str        ┆ f64       ┆ f64      ┆ ---      │
│          ┆ str      ┆ str        ┆ str      ┆     ┆            ┆           ┆          ┆ f64      │
╞══════════╪══════════╪════════════╪══════════╪═════╪════════════╪═══════════╪══════════╪══════════╡
│ S14010   ┆ 菊名店   ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.6326  ┆ 35.50049 ┆ 1732.0   │
│          ┆          ┆            ┆          ┆     ┆ 32         ┆           ┆          ┆          │
│ S14033   ┆ 阿久和店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4961  ┆ 35.45918 ┆ 1495.0   │
│          ┆          ┆            ┆          ┆     ┆ 43         ┆           ┆          ┆          │
│ S14040   ┆ 長津田店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4994  ┆ 35.52398 ┆ 1548.0   │
│          ┆          ┆            ┆          ┆     ┆ 46         ┆           ┆          ┆          │
│ S14050   ┆ 阿久和西 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4961  ┆ 35.45918 ┆ 1830.0   │
│          ┆ 店       ┆            ┆          ┆     ┆ 53         ┆           ┆          ┆          │
│ ...      ┆ ...      ┆ ...        ┆ ...      ┆ ... ┆ ...        ┆ ...       ┆ ...      ┆ ...      │
│ S14011   ┆ 日吉本町 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.6316  ┆ 35.54655 ┆ 890.0    │
│          ┆ 店       ┆            ┆          ┆     ┆ 33         ┆           ┆          ┆          │
│ S14048   ┆ 中川中央 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.5758  ┆ 35.54912 ┆ 1657.0   │
│          ┆ 店       ┆            ┆          ┆     ┆ 51         ┆           ┆          ┆          │
│ S14042   ┆ 新山下店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.6593  ┆ 35.43894 ┆ 1044.0   │
│          ┆          ┆            ┆          ┆     ┆ 47         ┆           ┆          ┆          │
│ S14006   ┆ 葛が谷店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.5633  ┆ 35.53573 ┆ 1886.0   │
│          ┆          ┆            ┆          ┆     ┆ 31         ┆           ┆          ┆          │
└──────────┴──────────┴────────────┴──────────┴─────┴────────────┴───────────┴──────────┴──────────┘

In [163]:
#顧客データ（df_customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まるデータを全項目抽出し、5件表示
#containsには正規表現も使用可能
df_dict['customer'].filter(pl.col('status_cd').str.contains(r'^[A-F]')).head(5)

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────┬─────┬──────────┬────────────┬────────────┬─────────┐
│ customer_ ┆ customer_n ┆ gender_cd ┆ gender ┆ ... ┆ address  ┆ applicatio ┆ applicatio ┆ status_ │
│ id        ┆ ame        ┆ ---       ┆ ---    ┆     ┆ ---      ┆ n_store_cd ┆ n_date     ┆ cd      │
│ ---       ┆ ---        ┆ str       ┆ str    ┆     ┆ str      ┆ ---        ┆ ---        ┆ ---     │
│ str       ┆ str        ┆           ┆        ┆     ┆          ┆ str        ┆ str        ┆ str     │
╞═══════════╪════════════╪═══════════╪════════╪═════╪══════════╪════════════╪════════════╪═════════╡
│ CS0314150 ┆ 宇多田     ┆ 1         ┆ 女性   ┆ ... ┆ 東京都渋 ┆ S13031     ┆ 20150529   ┆ D-20100 │
│ 00172     ┆ 貴美子     ┆           ┆        ┆     ┆ 谷区代々 ┆            ┆            ┆ 325-C   │
│           ┆            ┆           ┆        ┆     ┆ 木****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0154140 ┆ 奥野 陽子  ┆ 1         ┆ 女性   ┆ ... ┆ 東京都江 ┆ S13015     ┆ 20150722   ┆ B-20100 │
│ 00103     ┆            ┆           ┆        ┆     ┆ 東区北砂 ┆            ┆            ┆ 609-B   │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0112150 ┆ 芦田 沙耶  ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14011     ┆ 20150228   ┆ C-20100 │
│ 00048     ┆            ┆           ┆        ┆     ┆ 横浜市港 ┆            ┆            ┆ 421-9   │
│           ┆            ┆           ┆        ┆     ┆ 北区日吉 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ 本町**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
│ CS0294150 ┆ 梅田 里穂  ┆ 1         ┆ 女性   ┆ ... ┆ 千葉県浦 ┆ S12029     ┆ 20150610   ┆ D-20100 │
│ 00023     ┆            ┆           ┆        ┆     ┆ 安市富士 ┆            ┆            ┆ 918-E   │
│           ┆            ┆           ┆        ┆     ┆ 見****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0354150 ┆ 寺沢 真希  ┆ 9         ┆ 不明   ┆ ... ┆ 東京都世 ┆ S13035     ┆ 20141220   ┆ F-20101 │
│ 00029     ┆            ┆           ┆        ┆     ┆ 田谷区玉 ┆            ┆            ┆ 029-F   │
│           ┆            ┆           ┆        ┆     ┆ 川台**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
└───────────┴────────────┴───────────┴────────┴─────┴──────────┴────────────┴────────────┴─────────┘

In [165]:
#顧客データ（df_customer）から、ステータスコード（status_cd）の末尾が数字の1〜9で終わるデータを全項目抽出し、5件表示せよ。
df_dict['customer'].filter(pl.col('status_cd').str.contains(r'[1-9]$')).head(5)

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────┬─────┬──────────┬────────────┬────────────┬─────────┐
│ customer_ ┆ customer_n ┆ gender_cd ┆ gender ┆ ... ┆ address  ┆ applicatio ┆ applicatio ┆ status_ │
│ id        ┆ ame        ┆ ---       ┆ ---    ┆     ┆ ---      ┆ n_store_cd ┆ n_date     ┆ cd      │
│ ---       ┆ ---        ┆ str       ┆ str    ┆     ┆ str      ┆ ---        ┆ ---        ┆ ---     │
│ str       ┆ str        ┆           ┆        ┆     ┆          ┆ str        ┆ str        ┆ str     │
╞═══════════╪════════════╪═══════════╪════════╪═════╪══════════╪════════════╪════════════╪═════════╡
│ CS0012150 ┆ 田崎 美紀  ┆ 1         ┆ 女性   ┆ ... ┆ 東京都大 ┆ S13001     ┆ 20170605   ┆ 6-20090 │
│ 00145     ┆            ┆           ┆        ┆     ┆ 田区仲六 ┆            ┆            ┆ 929-2   │
│           ┆            ┆           ┆        ┆     ┆ 郷****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0335130 ┆ 安斎 遥    ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14033     ┆ 20150728   ┆ 6-20080 │
│ 00180     ┆            ┆           ┆        ┆     ┆ 横浜市旭 ┆            ┆            ┆ 506-5   │
│           ┆            ┆           ┆        ┆     ┆ 区善部町 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0112150 ┆ 芦田 沙耶  ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14011     ┆ 20150228   ┆ C-20100 │
│ 00048     ┆            ┆           ┆        ┆     ┆ 横浜市港 ┆            ┆            ┆ 421-9   │
│           ┆            ┆           ┆        ┆     ┆ 北区日吉 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ 本町**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
│ CS0404120 ┆ 川井 郁恵  ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14040     ┆ 20151101   ┆ 1-20091 │
│ 00191     ┆            ┆           ┆        ┆     ┆ 横浜市緑 ┆            ┆            ┆ 025-4   │
│           ┆            ┆           ┆        ┆     ┆ 区北八朔 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ 町****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0093150 ┆ 皆川 文世  ┆ 1         ┆ 女性   ┆ ... ┆ 東京都世 ┆ S13009     ┆ 20150319   ┆ 5-20080 │
│ 00023     ┆            ┆           ┆        ┆     ┆ 田谷区駒 ┆            ┆            ┆ 322-1   │
│           ┆            ┆           ┆        ┆     ┆ 沢****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
└───────────┴────────────┴───────────┴────────┴─────┴──────────┴────────────┴────────────┴─────────┘

In [167]:
#顧客データ（df_customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まり、末尾が数字の1〜9で終わるデータを全項目抽出し、5件表示せよ。
df_dict['customer'].filter(pl.col('status_cd').str.contains(r'^[A-F].*[1-9]$')).head(5)

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────┬─────┬──────────┬────────────┬────────────┬─────────┐
│ customer_ ┆ customer_n ┆ gender_cd ┆ gender ┆ ... ┆ address  ┆ applicatio ┆ applicatio ┆ status_ │
│ id        ┆ ame        ┆ ---       ┆ ---    ┆     ┆ ---      ┆ n_store_cd ┆ n_date     ┆ cd      │
│ ---       ┆ ---        ┆ str       ┆ str    ┆     ┆ str      ┆ ---        ┆ ---        ┆ ---     │
│ str       ┆ str        ┆           ┆        ┆     ┆          ┆ str        ┆ str        ┆ str     │
╞═══════════╪════════════╪═══════════╪════════╪═════╪══════════╪════════════╪════════════╪═════════╡
│ CS0112150 ┆ 芦田 沙耶  ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14011     ┆ 20150228   ┆ C-20100 │
│ 00048     ┆            ┆           ┆        ┆     ┆ 横浜市港 ┆            ┆            ┆ 421-9   │
│           ┆            ┆           ┆        ┆     ┆ 北区日吉 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ 本町**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
│ CS0225130 ┆ 島村       ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14022     ┆ 20150320   ┆ A-20091 │
│ 00105     ┆ 貴美子     ┆           ┆        ┆     ┆ 逗子市山 ┆            ┆            ┆ 115-7   │
│           ┆            ┆           ┆        ┆     ┆ の根**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
│ CS0015150 ┆ 水野 陽子  ┆ 9         ┆ 不明   ┆ ... ┆ 東京都大 ┆ S13001     ┆ 20150614   ┆ A-20100 │
│ 00096     ┆            ┆           ┆        ┆     ┆ 田区蒲田 ┆            ┆            ┆ 724-7   │
│           ┆            ┆           ┆        ┆     ┆ 本町**** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******   ┆            ┆            ┆         │
│ CS0136150 ┆ 西脇 季衣  ┆ 1         ┆ 女性   ┆ ... ┆ 千葉県千 ┆ S12013     ┆ 20150128   ┆ B-20100 │
│ 00053     ┆            ┆           ┆        ┆     ┆ 葉市美浜 ┆            ┆            ┆ 329-6   │
│           ┆            ┆           ┆        ┆     ┆ 区幕張西 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0204120 ┆ 小宮 薫    ┆ 1         ┆ 女性   ┆ ... ┆ 東京都板 ┆ S13020     ┆ 20150822   ┆ B-20081 │
│ 00161     ┆            ┆           ┆        ┆     ┆ 橋区東坂 ┆            ┆            ┆ 021-3   │
│           ┆            ┆           ┆        ┆     ┆ 下****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
└───────────┴────────────┴───────────┴────────┴─────┴──────────┴────────────┴────────────┴─────────┘

In [168]:
#店舗データ（df_store）から、電話番号（tel_no）が3桁-3桁-4桁のデータを全項目表示せよ。
df_dict['store'].filter(pl.col('tel_no').str.contains(r'^[0-9]{3}-[0-9]{3}-[0-9]{4}$')).head(5)

shape: (5, 10)
┌──────────┬──────────┬────────────┬──────────┬─────┬────────────┬───────────┬──────────┬──────────┐
│ store_cd ┆ store_na ┆ prefecture ┆ prefectu ┆ ... ┆ tel_no     ┆ longitude ┆ latitude ┆ floor_ar │
│ ---      ┆ me       ┆ _cd        ┆ re       ┆     ┆ ---        ┆ ---       ┆ ---      ┆ ea       │
│ str      ┆ ---      ┆ ---        ┆ ---      ┆     ┆ str        ┆ f64       ┆ f64      ┆ ---      │
│          ┆ str      ┆ str        ┆ str      ┆     ┆            ┆           ┆          ┆ f64      │
╞══════════╪══════════╪════════════╪══════════╪═════╪════════════╪═══════════╪══════════╪══════════╡
│ S12014   ┆ 千草台店 ┆ 12         ┆ 千葉県   ┆ ... ┆ 043-123-40 ┆ 140.118   ┆ 35.63559 ┆ 1698.0   │
│          ┆          ┆            ┆          ┆     ┆ 03         ┆           ┆          ┆          │
│ S13002   ┆ 国分寺店 ┆ 13         ┆ 東京都   ┆ ... ┆ 042-123-40 ┆ 139.4802  ┆ 35.70566 ┆ 1735.0   │
│          ┆          ┆            ┆          ┆     ┆ 08         ┆           ┆          ┆          │
│ S14010   ┆ 菊名店   ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.6326  ┆ 35.50049 ┆ 1732.0   │
│          ┆          ┆            ┆          ┆     ┆ 32         ┆           ┆          ┆          │
│ S14033   ┆ 阿久和店 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 045-123-40 ┆ 139.4961  ┆ 35.45918 ┆ 1495.0   │
│          ┆          ┆            ┆          ┆     ┆ 43         ┆           ┆          ┆          │
│ S14036   ┆ 相模原中 ┆ 14         ┆ 神奈川県 ┆ ... ┆ 042-123-40 ┆ 139.3716  ┆ 35.57327 ┆ 1679.0   │
│          ┆ 央店     ┆            ┆          ┆     ┆ 45         ┆           ┆          ┆          │
└──────────┴──────────┴────────────┴──────────┴─────┴────────────┴───────────┴──────────┴──────────┘

In [171]:
#顧客データ（df_customer）を生年月日（birth_day）で高齢順にソートし、先頭から全項目を5件表示せよ。
df_dict['customer'].sort('birth_day').head(5)

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────┬─────┬──────────┬────────────┬────────────┬─────────┐
│ customer_ ┆ customer_n ┆ gender_cd ┆ gender ┆ ... ┆ address  ┆ applicatio ┆ applicatio ┆ status_ │
│ id        ┆ ame        ┆ ---       ┆ ---    ┆     ┆ ---      ┆ n_store_cd ┆ n_date     ┆ cd      │
│ ---       ┆ ---        ┆ str       ┆ str    ┆     ┆ str      ┆ ---        ┆ ---        ┆ ---     │
│ str       ┆ str        ┆           ┆        ┆     ┆          ┆ str        ┆ str        ┆ str     │
╞═══════════╪════════════╪═══════════╪════════╪═════╪══════════╪════════════╪════════════╪═════════╡
│ CS0038130 ┆ 村山       ┆ 1         ┆ 女性   ┆ ... ┆ 東京都調 ┆ S13003     ┆ 20160214   ┆ 0-00000 │
│ 00014     ┆ 菜々美     ┆           ┆        ┆     ┆ 布市菊野 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 台****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0268130 ┆ 吉村 朝陽  ┆ 1         ┆ 女性   ┆ ... ┆ 神奈川県 ┆ S14026     ┆ 20150723   ┆ 0-00000 │
│ 00004     ┆            ┆           ┆        ┆     ┆ 藤沢市辻 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 堂元町** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│ CS0188110 ┆ 熊沢 美里  ┆ 1         ┆ 女性   ┆ ... ┆ 東京都清 ┆ S13018     ┆ 20150403   ┆ 0-00000 │
│ 00003     ┆            ┆           ┆        ┆     ┆ 瀬市野塩 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0278030 ┆ 内村 拓郎  ┆ 0         ┆ 男性   ┆ ... ┆ 神奈川県 ┆ S14027     ┆ 20151227   ┆ 0-00000 │
│ 00004     ┆            ┆           ┆        ┆     ┆ 藤沢市鵠 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 沼藤が谷 ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0138010 ┆ 天野 拓郎  ┆ 0         ┆ 男性   ┆ ... ┆ 千葉県船 ┆ S12013     ┆ 20160120   ┆ 0-00000 │
│ 00003     ┆            ┆           ┆        ┆     ┆ 橋市前原 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 東****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
└───────────┴────────────┴───────────┴────────┴─────┴──────────┴────────────┴────────────┴─────────┘

In [174]:
#顧客データ（df_customer）を生年月日（birth_day）で若い順にソートし、先頭から全項目を10件表示せよ。
# reverse=Trueにすることで降順にならべる
df_dict['customer'].sort('birth_day', reverse=True).head(5)

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────┬─────┬──────────┬────────────┬────────────┬─────────┐
│ customer_ ┆ customer_n ┆ gender_cd ┆ gender ┆ ... ┆ address  ┆ applicatio ┆ applicatio ┆ status_ │
│ id        ┆ ame        ┆ ---       ┆ ---    ┆     ┆ ---      ┆ n_store_cd ┆ n_date     ┆ cd      │
│ ---       ┆ ---        ┆ str       ┆ str    ┆     ┆ str      ┆ ---        ┆ ---        ┆ ---     │
│ str       ┆ str        ┆           ┆        ┆     ┆          ┆ str        ┆ str        ┆ str     │
╞═══════════╪════════════╪═══════════╪════════╪═════╪══════════╪════════════╪════════════╪═════════╡
│ CS0351140 ┆ 大村 美里  ┆ 1         ┆ 女性   ┆ ... ┆ 東京都世 ┆ S13035     ┆ 20150619   ┆ 6-20091 │
│ 00004     ┆            ┆           ┆        ┆     ┆ 田谷区桜 ┆            ┆            ┆ 205-6   │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ **       ┆            ┆            ┆         │
│ CS0221030 ┆ 福山       ┆ 9         ┆ 不明   ┆ ... ┆ 神奈川県 ┆ S14022     ┆ 20160909   ┆ 0-00000 │
│ 00002     ┆ はじめ     ┆           ┆        ┆     ┆ 逗子市逗 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 子****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0021130 ┆ 柴田       ┆ 1         ┆ 女性   ┆ ... ┆ 東京都小 ┆ S13002     ┆ 20160304   ┆ 0-00000 │
│ 00009     ┆ 真悠子     ┆           ┆        ┆     ┆ 金井市貫 ┆            ┆            ┆ 000-0   │
│           ┆            ┆           ┆        ┆     ┆ 井南町** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
│ CS0041150 ┆ 松井 京子  ┆ 1         ┆ 女性   ┆ ... ┆ 東京都中 ┆ S13004     ┆ 20161120   ┆ 1-20081 │
│ 00014     ┆            ┆           ┆        ┆     ┆ 野区上鷺 ┆            ┆            ┆ 231-1   │
│           ┆            ┆           ┆        ┆     ┆ 宮****** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ****     ┆            ┆            ┆         │
│ CS0021140 ┆ 山内 遥    ┆ 1         ┆ 女性   ┆ ... ┆ 東京都小 ┆ S13002     ┆ 20160920   ┆ 6-20100 │
│ 00010     ┆            ┆           ┆        ┆     ┆ 金井市貫 ┆            ┆            ┆ 510-1   │
│           ┆            ┆           ┆        ┆     ┆ 井北町** ┆            ┆            ┆         │
│           ┆            ┆           ┆        ┆     ┆ ******** ┆            ┆            ┆         │
└───────────┴────────────┴───────────┴────────┴─────┴──────────┴────────────┴────────────┴─────────┘

In [176]:
#レシート明細データ（df_receipt）に対し、1件あたりの売上金額（amount）が高い順にランクを付与し、先頭から10件表示せよ。
#項目は顧客ID（customer_id）、売上金額（amount）、付与したランクを表示させること。なお、売上金額（amount）が等しい場合は同一順位を付与するものとする。
df_dict['receipt'].select([
    pl.col('customer_id'),
    pl.col('amount'),
    pl.col('amount').rank(method='min', reverse=True).alias('ranking')
]).sort('ranking').head(10)

shape: (10, 3)
┌────────────────┬────────┬─────────┐
│ customer_id    ┆ amount ┆ ranking │
│ ---            ┆ ---    ┆ ---     │
│ str            ┆ i64    ┆ u32     │
╞════════════════╪════════╪═════════╡
│ CS011415000006 ┆ 10925  ┆ 1       │
│ ZZ000000000000 ┆ 6800   ┆ 2       │
│ CS028605000002 ┆ 5780   ┆ 3       │
│ CS015515000034 ┆ 5480   ┆ 4       │
│ ...            ┆ ...    ┆ ...     │
│ ZZ000000000000 ┆ 5440   ┆ 7       │
│ CS021515000089 ┆ 5440   ┆ 7       │
│ CS015515000083 ┆ 5280   ┆ 9       │
│ CS017414000114 ┆ 5280   ┆ 9       │
└────────────────┴────────┴─────────┘

※rankメソッドについて  
デフォルトでは'amount'の昇順（小さいものから順に）にランク付けされるため、  
reverse=Trueにして降順にランク付けしている。ランク順に表示されるわけではないので最後にsortする必要あり。  
引数methodは同一値（重複値）の処理を指定するもので、  
method='min'とすると最小値が順位となる。1位、2位タイ、2位タイ、4位のようにしたいときに使う。  
参考：https://note.nkmk.me/python-pandas-rank/

In [178]:
# Datarfame長をカウント。pandasと同じ
len(df_dict['receipt'])

104681